# -*- coding: utf-8 -*-
"""multiple_linear_regression-Advertisement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVSdzlkSb_JwOXqteLNi2dc16FEBEoNk
"""

import numpy as np
import pandas as pd
df=pd.read_csv('/content/advertising.csv')
df

df.head()

df.tail()

df.dtypes

df.columns

print(df.isna().sum())

x=df.iloc[:,:-1]
x

y=df.iloc[:,-1]
y

#seaborn()
#regplot
import seaborn as snb
snb.regplot(x=df['TV'],y=y,color='red')

snb.regplot(x=df['Radio'],y=y,color='blue')

snb.regplot(x=df['Newspaper'],y=y,color='yellow')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

x_test

y_test

y_train

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

print(model.predict([[60.5,150,50]]))

df1=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_pred,'Difference':y_test-y_pred})
df1

print("slope is",model.coef_)
print("constant is",model.coef_)

l1=model.coef_
print("slope of TV is",l1[0])

print("slope of Radio is",l1[1])

print("slope of Newspaper is",l1[2])

print(list(zip(x,model.coef_)))

from sklearn.metrics import mean_absolute_error
print("error is ",mean_absolute_error(y_test,y_pred))

from sklearn.metrics import mean_absolute_percentage_error
print("error is ",mean_absolute_percentage_error(y_test,y_pred))

from sklearn.metrics import mean_squared_error
data=mean_squared_error(y_test,y_pred)
print("error is ",data)

from sklearn.metrics import r2_score
print("error is ",r2_score(y_test,y_pred))